"""add_live_transcript_segment

Revision ID: 0f2832cd2568
Revises: dd86116921c4
Create Date: 2026-06-22 19:22:52.710096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f2832cd2568'
down_revision: Union[str, None] = 'dd86116921c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LiveTranscriptSegment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interviewId', sa.String(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestampMs', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interviewId'], ['Interview.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('candidate_email_org_unique'), table_name='Candidate', postgresql_where='(email IS NOT NULL)')
    op.alter_column('Interview', 'agentStatus',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Interview', 'agentStatus',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('candidate_email_org_unique'), 'Candidate', ['organizationId', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.drop_table('LiveTranscriptSegment')
    # ### end Alembic commands ###
