"""candidate_portal_fields

Revision ID: 2c4118935894
Revises: 34c9350f98f8
Create Date: 2026-06-18 00:23:18.185402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c4118935894'
down_revision: Union[str, None] = '34c9350f98f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Candidate', sa.Column('passwordHash', sa.String(), nullable=True))
    op.add_column('Candidate', sa.Column('jobId', sa.String(), nullable=True))
    op.add_column('Candidate', sa.Column('status', sa.String(), nullable=False, server_default='applied'))
    op.add_column('Candidate', sa.Column('portalCreatedAt', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'Candidate', 'Job', ['jobId'], ['id'])
    op.add_column('Job', sa.Column('signupToken', sa.String(), nullable=True))
    op.add_column('Job', sa.Column('interviewMode', sa.String(), nullable=False, server_default='live'))
    op.add_column('Job', sa.Column('autoInterviewThreshold', sa.Integer(), nullable=False, server_default='60'))
    op.execute('UPDATE "Job" SET "signupToken" = gen_random_uuid()::text WHERE "signupToken" IS NULL')
    op.alter_column('Job', 'signupToken', nullable=False)
    op.create_unique_constraint(None, 'Job', ['signupToken'])
    op.execute('CREATE UNIQUE INDEX candidate_portal_email_unique ON "Candidate" (email) WHERE "passwordHash" IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Job', type_='unique')
    op.drop_column('Job', 'autoInterviewThreshold')
    op.drop_column('Job', 'interviewMode')
    op.drop_column('Job', 'signupToken')
    op.drop_constraint(None, 'Candidate', type_='foreignkey')
    op.drop_column('Candidate', 'portalCreatedAt')
    op.drop_column('Candidate', 'status')
    op.drop_column('Candidate', 'jobId')
    op.drop_column('Candidate', 'passwordHash')
    op.execute('DROP INDEX IF EXISTS candidate_portal_email_unique')
    # ### end Alembic commands ###
