"""remove_audio_video_columns

Revision ID: 34c9350f98f8
Revises: c183f4948e9e
Create Date: 2026-06-17 22:17:44.607892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '34c9350f98f8'
down_revision: Union[str, None] = 'c183f4948e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Interview', 'videoBehavioralMetrics')
    op.drop_column('Interview', 'videoMetricsConsentAt')
    op.drop_column('Interview', 'audioSignals')
    op.drop_column('Interview', 'recordingPath')
    op.create_unique_constraint(None, 'OrganizationMember', ['organizationId', 'userId'])
    op.create_unique_constraint(None, 'RolePermission', ['roleId', 'permissionId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RolePermission', type_='unique')
    op.drop_constraint(None, 'OrganizationMember', type_='unique')
    op.add_column('Interview', sa.Column('recordingPath', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Interview', sa.Column('audioSignals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Interview', sa.Column('videoMetricsConsentAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Interview', sa.Column('videoBehavioralMetrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
