"""redesign_intelligence_schema

Revision ID: 765bf2272b9d
Revises: 966c6d7d0867
Create Date: 2026-06-23 20:56:28.130095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '765bf2272b9d'
down_revision: Union[str, None] = '966c6d7d0867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Decision', sa.Column('reasonsToHire', sa.JSON(), nullable=True))
    op.add_column('Decision', sa.Column('reasonsToReject', sa.JSON(), nullable=True))
    op.drop_column('Decision', 'comparisonNotes')
    op.drop_column('Decision', 'riskFactors')
    op.drop_column('Decision', 'hireConfidence')
    op.drop_column('Decision', 'signalBreakdown')
    op.add_column('InterviewAnalysis', sa.Column('pacingScore', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('fillerScore', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('energyLevel', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('dominantTone', sa.String(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('emotionalVariance', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('truthfulnessScore', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('depthScore', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('resumeConsistencyScore', sa.Float(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('inconsistencies', sa.JSON(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('depthNotes', sa.JSON(), nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('workStyleNotes', sa.JSON(), nullable=True))
    op.drop_column('InterviewAnalysis', 'engagementScore')
    op.drop_column('InterviewAnalysis', 'consistencyScore')
    op.drop_column('InterviewAnalysis', 'behavioralMetrics')
    op.drop_column('InterviewAnalysis', 'hesitationScore')
    op.drop_column('InterviewAnalysis', 'cognitiveSignals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewAnalysis', sa.Column('cognitiveSignals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('hesitationScore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('behavioralMetrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('consistencyScore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('InterviewAnalysis', sa.Column('engagementScore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('InterviewAnalysis', 'workStyleNotes')
    op.drop_column('InterviewAnalysis', 'depthNotes')
    op.drop_column('InterviewAnalysis', 'inconsistencies')
    op.drop_column('InterviewAnalysis', 'resumeConsistencyScore')
    op.drop_column('InterviewAnalysis', 'depthScore')
    op.drop_column('InterviewAnalysis', 'truthfulnessScore')
    op.drop_column('InterviewAnalysis', 'emotionalVariance')
    op.drop_column('InterviewAnalysis', 'dominantTone')
    op.drop_column('InterviewAnalysis', 'energyLevel')
    op.drop_column('InterviewAnalysis', 'fillerScore')
    op.drop_column('InterviewAnalysis', 'pacingScore')
    op.add_column('Decision', sa.Column('signalBreakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Decision', sa.Column('hireConfidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Decision', sa.Column('riskFactors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Decision', sa.Column('comparisonNotes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('Decision', 'reasonsToReject')
    op.drop_column('Decision', 'reasonsToHire')
    # ### end Alembic commands ###
