"""drop_rawanalysis_column

Revision ID: 966c6d7d0867
Revises: 0f2832cd2568
Create Date: 2026-06-22 23:35:47.220328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '966c6d7d0867'
down_revision: Union[str, None] = '0f2832cd2568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InterviewAnalysis', 'rawAnalysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewAnalysis', sa.Column('rawAnalysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
