"""initial schema

Revision ID: c183f4948e9e
Revises: 
Create Date: 2026-06-17 20:52:19.432675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c183f4948e9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('Permission',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('Role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('ORGANIZATION', 'JOB', 'PLATFORM', name='rolescope'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('emailVerified', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('isPlatformAdmin', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Candidate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedInUrl', sa.String(), nullable=True),
    sa.Column('linkedInText', sa.Text(), nullable=True),
    sa.Column('githubUrl', sa.String(), nullable=True),
    sa.Column('portfolioUrl', sa.String(), nullable=True),
    sa.Column('resumeText', sa.Text(), nullable=True),
    sa.Column('resumeFilePath', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('roleId', sa.String(), nullable=False),
    sa.Column('invitedById', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('acceptedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitedById'], ['User.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('hiringManagerId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hiringManagerId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OrganizationMember',
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('roleId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('organizationId', 'userId'),
    sa.UniqueConstraint('organizationId', 'userId')
    )
    op.create_table('RolePermission',
    sa.Column('roleId', sa.String(), nullable=False),
    sa.Column('permissionId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['Permission.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('roleId', 'permissionId'),
    sa.UniqueConstraint('roleId', 'permissionId')
    )
    op.create_table('JobApplication',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('candidateId', sa.String(), nullable=False),
    sa.Column('jobId', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'TALENT_REVIEW', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'DECISION', 'HIRED', 'REJECTED', name='pipelinestage'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['Candidate.id'], ),
    sa.ForeignKeyConstraint(['jobId'], ['Job.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateId', 'jobId')
    )
    op.create_table('JobAssignment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jobId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('assignmentRole', sa.Enum('HIRING_MANAGER', 'INTERVIEWER', name='JobAssignmentRole'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['Job.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobId', 'userId', 'assignmentRole')
    )
    op.create_table('Note',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidateId', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['candidateId'], ['Candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Decision',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('applicationId', sa.String(), nullable=False),
    sa.Column('hireConfidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('riskFactors', sa.JSON(), nullable=True),
    sa.Column('comparisonNotes', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('signalBreakdown', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['JobApplication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicationId')
    )
    op.create_table('Interview',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('applicationId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'RECORDED', 'TRANSCRIBED', 'ANALYZED', name='interviewstatus'), nullable=False),
    sa.Column('scheduledAt', sa.DateTime(), nullable=True),
    sa.Column('durationMinutes', sa.Integer(), nullable=False),
    sa.Column('meetingUrl', sa.String(), nullable=True),
    sa.Column('recordingPath', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audioSignals', sa.JSON(), nullable=True),
    sa.Column('videoMetricsConsentAt', sa.DateTime(), nullable=True),
    sa.Column('videoBehavioralMetrics', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['JobApplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TalentProfile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('applicationId', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experienceYears', sa.Integer(), nullable=True),
    sa.Column('roleFitScore', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('hiddenSignals', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['JobApplication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicationId')
    )
    op.create_table('InterviewAnalysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interviewId', sa.String(), nullable=False),
    sa.Column('hesitationScore', sa.Float(), nullable=True),
    sa.Column('confidenceScore', sa.Float(), nullable=True),
    sa.Column('clarityScore', sa.Float(), nullable=True),
    sa.Column('consistencyScore', sa.Float(), nullable=True),
    sa.Column('engagementScore', sa.Float(), nullable=True),
    sa.Column('cognitiveSignals', sa.JSON(), nullable=True),
    sa.Column('behavioralMetrics', sa.JSON(), nullable=True),
    sa.Column('riskFlags', sa.JSON(), nullable=True),
    sa.Column('interviewerQuality', sa.JSON(), nullable=True),
    sa.Column('rawAnalysis', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interviewId'], ['Interview.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interviewId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InterviewAnalysis')
    op.drop_table('TalentProfile')
    op.drop_table('Interview')
    op.drop_table('Decision')
    op.drop_table('Note')
    op.drop_table('JobAssignment')
    op.drop_table('JobApplication')
    op.drop_table('RolePermission')
    op.drop_table('OrganizationMember')
    op.drop_table('Job')
    op.drop_table('Invite')
    op.drop_table('Candidate')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('Organization')
    # ### end Alembic commands ###
